name: Build
on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: 'x64'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build with meson
        run: |
          pip install meson
          pip install ninja
          
          meson setup build
          meson compile -C build
          cd build/examples/
          ./smiley.exe

      - uses: actions/upload-artifact@v4
        with:
          name: smiley-windows-meson
          path: ./build/examples/*
          
      - name: Build with cmake
        run: |
          cmake .
          cmake --build .
          cd examples/Debug/
          ./smiley.exe
      - uses: actions/upload-artifact@v4
        with:
          name: smiley-windows-cmake
          path: ./examples/Debug/*
          
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build with meson
        run: |
          pip install meson
          pip install ninja
          
          meson setup build
          meson compile -C build
          cd build/examples/
          ./smiley
      - uses: actions/upload-artifact@v4
        with:
          name: smiley-linux-meson
          path: ./build/examples/*

      - name: Build with cmake
        run: |
          cmake .
          cmake --build .
          cd build/examples/
          ./smiley
      - uses: actions/upload-artifact@v4
        with:
          name: smiley-linux-cmake
          path: ./build/examples/*
          
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build with meson
        run: |
          pip install meson
          pip install ninja
          
          meson setup build
          meson compile -C build
          cd build/examples/
          ./smiley
      - uses: actions/upload-artifact@v4
        with:
          name: smiley-macos-meson
          path: ./build/examples/*

      - name: Build with cmake
        run: |
          cmake .
          cmake --build .
          cd build/examples/
          ./smiley
      - uses: actions/upload-artifact@v4
        with:
          name: smiley-macos-cmake
          path: ./build/examples/*
          
